#!/usr/bin/env bash
# Bicep self-provisioning demo — Dagster as Infrastructure-as-Code orchestrator.
#
# WHAT THIS DEMONSTRATES
#   The first asset in the graph is a Bicep deployment. Once it succeeds,
#   downstream data assets can use the storage account it just created. This
#   is the "Dagster owns the infra" pattern — useful for ephemeral environments,
#   per-tenant provisioning, or treating infra as just another asset.
#
# Pipeline:
#   bicep_asset (provisions storage)
#         │
#         └─→ synthetic_data_generator → dataframe_to_adls (uses provisioned storage)
#
# PREREQS
#   1. Azure subscription, az CLI signed in.
#   2. Bicep installed (`az bicep install` — one-time).
#   3. Microsoft.Storage provider registered:
#        az provider register --namespace Microsoft.Storage --wait
#   4. AZURE_SUBSCRIPTION_ID env var set:
#        export AZURE_SUBSCRIPTION_ID=$(az account show --query id -o tsv)
#
# COST
#   Same as the ADLS demo (~$0.05/month). The Bicep deployment is free; the
#   storage account it creates costs the same as if you'd run `az storage
#   account create` directly.
#
# TEARDOWN
#   az group delete --name dagster-demo-bicep-rg --yes

set -euo pipefail
PROJECT_DIR="${1:-bicep-self-provision-demo}"

if [ -z "${AZURE_SUBSCRIPTION_ID:-}" ]; then
  echo "ERROR: set AZURE_SUBSCRIPTION_ID first:"
  echo "    export AZURE_SUBSCRIPTION_ID=\$(az account show --query id -o tsv)"
  exit 1
fi

# Provision the resource group (the Bicep template will fill it in)
RG=dagster-demo-bicep-rg
LOC=eastus
echo ">>> Creating resource group $RG (RG only — Bicep adds the rest)"
az group create --name "$RG" --location "$LOC" --output none

echo ">>> Scaffolding canonical Dagster project at $PROJECT_DIR"
uvx create-dagster@latest project "$PROJECT_DIR" --no-uv-sync >/dev/null
cd "$PROJECT_DIR"
PKG="$(ls src/ | head -1)"

uv add -q pandas pyarrow azure-mgmt-resource azure-identity
uv add --dev -q dagster-dg-cli dagster-webserver

# Write the Bicep template (creates a storage account + container)
mkdir -p bicep
cat > bicep/main.bicep <<'BICEP'
// Provisions a small ADLS Gen2 storage account + a 'demo' container.
// Outputs the storage account name so downstream Dagster assets can read it.

@description('Storage account name (must be globally unique, lowercase, 3-24 chars)')
param storageAccountName string = 'dagdemo${uniqueString(resourceGroup().id)}'

@description('Region')
param location string = resourceGroup().location

resource sa 'Microsoft.Storage/storageAccounts@2023-01-01' = {
  name: storageAccountName
  location: location
  sku: { name: 'Standard_LRS' }
  kind: 'StorageV2'
  properties: {
    isHnsEnabled: true
    accessTier: 'Hot'
    minimumTlsVersion: 'TLS1_2'
  }
}

resource container 'Microsoft.Storage/storageAccounts/blobServices/containers@2023-01-01' = {
  name: '${sa.name}/default/demo'
  properties: { publicAccess: 'None' }
}

output storageAccountName string = sa.name
output blobEndpoint string = sa.properties.primaryEndpoints.blob
BICEP

CLI="uvx --from dagster-community-components-cli dagster-component"

echo ">>> Installing 3 community components"
$CLI add bicep_asset              --auto-install
$CLI add synthetic_data_generator --auto-install
$CLI add dataframe_to_adls        --auto-install

echo ">>> Writing demo defs.yaml"

cat > "src/$PKG/defs/bicep_asset/defs.yaml" <<EOF
type: $PKG.components.bicep_asset.component.BicepAssetComponent
attributes:
  asset_name: provisioned_storage
  resource_group: $RG
  deployment_name: dagster-bicep-demo
  bicep_file: bicep/main.bicep
  subscription_id: $AZURE_SUBSCRIPTION_ID
  group_name: infrastructure
  description: |
    Provisions an ADLS Gen2 storage account + 'demo' container via Bicep.
    Outputs (storageAccountName, blobEndpoint) are surfaced as Dagster metadata.
EOF

cat > "src/$PKG/defs/synthetic_data_generator/defs.yaml" <<EOF
type: $PKG.components.synthetic_data_generator.component.SyntheticDataGeneratorComponent
attributes:
  asset_name: orders_raw
  schema_type: orders
  row_count: 100
  random_state: 42
  description: 100 synthetic orders, written after the Bicep deployment lands
  group_name: data
  deps:
    - provisioned_storage
EOF

# Wire dataframe_to_adls to read account name + key from env vars (set after
# the Bicep deployment runs and you query for the generated account name).
cat > "src/$PKG/defs/dataframe_to_adls/defs.yaml" <<EOF
type: $PKG.components.dataframe_to_adls.component.DataframeToAdlsComponent
attributes:
  asset_name: orders_in_provisioned_adls
  upstream_asset_key: orders_raw
  account_name_env_var: AZURE_STORAGE_ACCOUNT_NAME
  account_key_env_var: AZURE_STORAGE_ACCOUNT_KEY
  container: demo
  blob_path: bicep_provisioned/orders.parquet
  format: parquet
  compression: snappy
  group_name: data
EOF

# Note: the storage account name is generated by Bicep at deploy time
# (uniqueString), so we can't bake it into defs.yaml ahead of time. The
# pattern in production is: read the bicep_asset's output metadata at runtime
# (via Dagster's MaterializationEvent + asset_check resolver) and pass it
# to the dataframe_to_adls asset's compute.
#
# For this demo, simpler path: read the storage account name with az CLI
# right before launching, then export the env var.

cat <<MSG

>>> Setup complete (project scaffolded; Bicep template at bicep/main.bicep).

Materialize the Bicep asset first:
    cd $PROJECT_DIR
    uv run dg launch --assets provisioned_storage

Inspect what Bicep created:
    az resource list -g $RG -o table

Then read the storage account name and write to it from Dagster:
    SA=\$(az storage account list -g $RG --query '[0].name' -o tsv)
    KEY=\$(az storage account keys list -g $RG -n \$SA --query '[0].value' -o tsv)
    export AZURE_STORAGE_ACCOUNT_NAME=\$SA
    export AZURE_STORAGE_ACCOUNT_KEY=\$KEY

    # Patch the dataframe_to_adls defs to point at the new account, then run
    # the rest of the pipeline. (See the walkthrough md for the full pattern.)

Teardown:
    az group delete --name $RG --yes
MSG
